[package]
name = "project-euler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "problem_001"
path = "src/bin/problem_001.rs"

[[bin]]
name = "problem_002"
path = "src/bin/problem_002.rs"

[[bin]]
name = "problem_003"
path = "src/bin/problem_003.rs"

[dependencies]
